### ISSUE TITLE
Message `Project has been successfully deleted` is shown before project actually deleted

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#188]
This happens because deleting project in openshift is long running operation that is not finished when `odo project delete` exits. Instead project's status first moved to `Terminating` phase and only after that project disappears from `oc get project' list of projects.

Here is an example of yaml configuration tor project resource in `terminating` phase:
``` yaml
oc.exe get project -o json --watch-only
{
    "kind": "Project",
    "apiVersion": "v1",
    "metadata": {
        "name": "a1",
        "selfLink": "/apis/project.openshift.io/v1/projects/a1",
        "uid": "d57f94f1-c6d6-11e8-a3a5-080027c7413d",
        "resourceVersion": "12957",
        "creationTimestamp": "2018-10-03T06:37:44Z",
        "deletionTimestamp": "2018-10-03T06:40:39Z",
        "annotations": {
            "openshift.io/description": "",
            "openshift.io/display-name": "",
            "openshift.io/requester": "developer",
            "openshift.io/sa.scc.mcs": "s0:c12,c4",
            "openshift.io/sa.scc.supplemental-groups": "1000140000/10000",
            "openshift.io/sa.scc.uid-range": "1000140000/10000"
        }
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Terminating"
    }
}
{
    "kind": "Project",
    "apiVersion": "v1",
    "metadata": {
        "name": "a1",
        "selfLink": "/apis/project.openshift.io/v1/projects/a1",
        "creationTimestamp": null
    },
    "spec": {},
    "status": {}
}
```
