### ISSUE TITLE
Long load time when running on Eclipse Che

### ISSUE THREAD

**Issue by virtuakazib** [redhat-developer/vscode-openshift-tools#2179]
Environment

Eclipse Che: 7.32.0
OpenShift: 4.6.28

When opening a new Eclipse Che workspace with the OpenShift connector plugin it takes roughly 3 minutes before the plugin is loaded/initialized.  Meaning 3 minutes until the Kubernetes and OpenShift view appear on the left and that OpenShift commands are available to run.

Is there some configuration missing that might reduce this load time?

Sample Devfile:
```
apiVersion: 1.0.0
metadata:
  name: openshfit-nodejs-webapp
attributes:
  persistVolumes: 'false'
projects:
  - name: react-web-app
    source:
      location: 'https://github.com/che-samples/react-web-app'
      type: git
components:
  - id: che-incubator/typescript/latest
    type: chePlugin
  - id: redhat/vscode-openshift-connector/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: nodejs
        port: 3000
    memoryLimit: 1500Mi
    type: dockerimage
    alias: nodejs
    image: 'quay.io/eclipse/che-nodejs12-community@sha256:84540fa219bd0ee7316c921e51c4f30ee083404f282ab555f982fcfb47f0cd49'
commands:
  - name: 1. Install Yarn 2
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/react-web-app'
        type: exec
        command: yarn set version berry
        component: nodejs
  - name: 2. Install all required dependencies
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/react-web-app'
        type: exec
        command: yarn install
        component: nodejs
  - name: 3. Build the app
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/react-web-app'
        type: exec
        command: yarn build
        component: nodejs
  - name: 4. Run the app
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/react-web-app'
        type: exec
        command: yarn start
        component: nodejs
  - name: 5. Launch tests
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/react-web-app'
        type: exec
        command: yarn test
        component: nodejs

```
