### ISSUE TITLE
Resource yaml without name can be pushed but no resource is created nor pull/diff do anything

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#2679]
This is **IT No 36**

**Steps:**
1. EXEC: File > New > YML file -> paste the following resource without name
```
"apiVersion: v1
metadata:
  labels:
    jedi: yoda
data:
  username: YWRtaW4=222
  password: MWYyZDFlMmU2N2Rm
kind: Secret
type: Opaque"
```
**Result:**
Nothing happens. No resource is created, no error is displayed.

**Expected result:**
Error notification "resource could not be retrieved (details: name missing)"
