### ISSUE TITLE
Show Helm charts from all Helm repos in the Helm chart explorer

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3113]
The only Helm repo that is available in the Helm Chart explorer is the OpenShift Helm repo, even if the user has configured additional ones outside of VS Code OpenShift. This is a problem, since many of the charts in the OpenShift Helm repo (including most of the interesting ones like Postgres, Redis, and Jenkins) only work on OpenShift, since they rely on Routes or DeploymentConfigs.

In order to get the extension to work better with other Kubernetes clusters, I think that we should:
- Show all the charts from all the Helm repos that the user has configured in the Helm chart explorer webview
- Add some sort of indicator, perhaps a [small chip](https://mui.com/material-ui/react-chip/#sizes-chip), to show which charts come from which repo
- Add a list of checkboxes in the Helm chart explorer to show/hide charts for a particular repo

There is a mechanism to add/remove Helm repositories in the Kubernetes extension, so I don't think we need to do that as part of this issue.

**Comment by datho7561** [comment]
I think @msivasubramaniaan mentioned he was working on this

**Comment by msivasubramaniaan** [comment]
Hello @mohitsuman and @datho7561 

When we plan to integrate the CLI approach for getting all the installed Helm repos, `helm search repo -l -o=json` there were some discrepancies between the web API call and the CLI on helm. 

- **Web API call(https://charts.openshift.io/index.yaml) - wavefront**
```
- annotations:
      charts.openshift.io/digest: sha256:27d8a54382f1c39c55f9239bc7e17195d4c416742113fcaae1013b93b1689be0
      charts.openshift.io/lastCertifiedTimestamp: '2023-04-14T19:48:53.916688+00:00'
      charts.openshift.io/provider: VMWare
      charts.openshift.io/providerType: partner
      charts.openshift.io/submissionTimestamp: '2023-04-14T19:55:53.925857+00:00'
      charts.openshift.io/supportedOpenShiftVersions: '>=4.6'
      charts.openshift.io/testedOpenShiftVersion: '4.9'
    apiVersion: v2
    appVersion: 1.16.0
    dependencies:
    - condition: kubeStateMetrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: ^4.16.0
    description: Wavefront Collector for Kubernetes
    digest: 16892309c6c0be3f669be955f0ca162e432de28af631ad8e781912dd6f7cead3
    home: https://www.wavefront.com
    keywords:
    - metric
    - monitoring
    - observability
    - alerting
    kubeVersion: '>= 1.19'
    maintainers:
    - email: akodali@vmware.com
      name: akodali18
    - email: pginwoo@vmware.com
      name: ginwoopak
    - email: jalvis@vmware.com
      name: iplay88keys
    - email: bjerry@vmware.com
      name: jerrybelmonte
    - email: jcornish@vmware.com
      name: johncornish
    - email: jgee@vmware.com
      name: josephgee
    - email: jyuqi@vmware.com
      name: jyuqi
    - email: matthewco@vmware.com
      name: m25n
    - email: mamichael@vmware.com
      name: mmichael
    - email: pselvaganesa@vmware.com
      name: priyaselvaganesan
    name: wavefront
    sources:
    - https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
    - https://github.com/wavefrontHQ/wavefront-proxy
    urls:
    - https://github.com/openshift-helm-charts/charts/releases/download/wavefronthq-wavefront-1.13.1/wavefront-1.13.1.tgz
    version: 1.13.1 
```

- **CLI response - wavefront** 
```
annotations:
  charts.openshift.io/name: wavefront
apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: kubeStateMetrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: ^4.16.0
description: Wavefront Collector for Kubernetes
home: https://www.wavefront.com
keywords:
- metric
- monitoring
- observability
- alerting
kubeVersion: '>= 1.19'
maintainers:
- email: akodali@vmware.com
  name: akodali18
- email: pginwoo@vmware.com
  name: ginwoopak
- email: jalvis@vmware.com
  name: iplay88keys
- email: bjerry@vmware.com
  name: jerrybelmonte
- email: jcornish@vmware.com
  name: johncornish
- email: jgee@vmware.com
  name: josephgee
- email: jyuqi@vmware.com
  name: jyuqi
- email: matthewco@vmware.com
  name: m25n
- email: mamichael@vmware.com
  name: mmichael
- email: pselvaganesa@vmware.com
  name: priyaselvaganesan
name: wavefront
sources:
- https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
- https://github.com/wavefrontHQ/wavefront-proxy
version: 1.13.1
```
provider, providerType, icon and many more keys  were missing. How shall we proceed especially on filter based workflow.

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/7a4e2696-058f-4b4d-9866-a0362783e5f4)

Are you guys okay with adding **static icons** and removing the **Provider and Provider Type** filtering and moving forward the filtering will be only on **repository** level.
