### ISSUE TITLE
Migrate  "odo deploy"

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#4482]

**Comment by lgrossma** [comment]
Odo deploy basically consists of 2 steps - build the application and creating a deployment (probably more steps could be added if needed). The deploy command has to be defined in a devfile.

Build step:
1. The user must have a defined Dockerfile
2. Upon calling `odo deploy` the odo first builds a docker image locally (using podman/docker) as defined in the Dockerfile
3. The image is pushed into a registry (The user must setup this connection somehow. In odo, there is a command/setting `preference set ImageRegistry $registry`)

Create deployment step:
1. The user must have a defined Deployment.yaml
2. Odo creates a deployment based on this file

Here is how odo decides what to do based on a devfile
```
commands:
- apply:
    component: image-build
  id: build-image
- apply:
    component: kubernetes-deploy
  id: deployk8s
- composite:
    commands:
    - build-image
    - deployk8s
    group:
      isDefault: true
      kind: deploy
  id: deploy
components:
- image:
    dockerfile:
      buildContext: .
      rootRequired: false
      uri: Dockerfile
    imageName: nodejs-image:latest
  name: image-build
- attributes:
    deployment/container-port: 3001
    deployment/cpuRequest: 10m
    deployment/memoryRequest: 50Mi
    deployment/replicas: 1
  kubernetes:
    endpoints:
    - name: http-3001
      path: /
      secure: true
      targetPort: 3001
    uri: deploy.yaml
  name: kubernetes-deploy
metadata:
  attributes:
    alpha.dockerimage-port: 3001
  description: Stack with Node.js 18
  displayName: Node.js Runtime
  language: JavaScript
  name: nodejs-starter
  projectType: Node.js
  provider: Red Hat
  supportUrl: https://github.com/devfile-samples/devfile-support#support-information
  tags:
  - Node.js
  - Express
  - ubi8
  version: 3.0.0
parent:
  id: nodejs
  registryUrl: https://registry.devfile.io
  version: 2.2.0
schemaVersion: 2.2.0
```
The deploy command here is defined as
```
- composite:
    commands:
    - build-image
    - deployk8s
    group:
      isDefault: true
      kind: deploy
  id: deploy
```
First, it executes command `build-image` that is defined as
```
- apply:
    component: image-build
  id: build-image
```
This applies a component with name `image-build` that is defined by
```
- image:
    dockerfile:
      buildContext: .
      rootRequired: false
      uri: Dockerfile
    imageName: nodejs-image:latest
  name: image-build
```
Odo then uses referenced Dockerfile to build a docker image. After the build is finished, it pushes the image to a user specified repository.

Second, it executes command `deployk8s`, which is defined as
```
- apply:
    component: kubernetes-deploy
  id: deployk8s
```
This applies to a component with name `kubernetes-deploy`, that is defined by
```
 kubernetes:
    endpoints:
    - name: http-3001
      path: /
      secure: true
      targetPort: 3001
    uri: deploy.yaml
  name: kubernetes-deploy
```
Odo then uses referenced deploy.yaml file to create a Kubernetes deployment
