### ISSUE TITLE
VS Code OpenShift Toolkit extension does not detect connection on the cluster it is deployed on

### ISSUE THREAD

**Issue by vrubezhny** [redhat-developer/vscode-openshift-tools#4535]
VS Code OpenShift Toolkit extension does not detect connection on the cluster it is deployed on even if VS Code Kubernetes is able to detect it.

See the details and Steps to Reproduce at: https://github.com/eclipse-che/che/issues/23183

**Comment by adietish** [comment]
I can reproduce this locally. I have the Red Hat Sandbox set as current cluster:
```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://api.sandbox-XXXXX.openshiftapps.com:6443
  name: api-sandbox-XXXXX-openshiftapps-com:6443
contexts:
- context:
    cluster: api-sandbox-XXXXX-openshiftapps-com:6443
    namespace: adietish-dev
    user: adietish/api-sandbox-XXXXX-openshiftapps-com:6443
  name: adietish-dev/api-sandbox-XXXXX-openshiftapps-com:6443/adietish
current-context: adietish-dev/api-sandbox-XXXXX-openshiftapps-com:6443/adietish
kind: Config
preferences: {}
users:
- name: adietish/api-sandbox-XXXXX-openshiftapps-com:6443
  user:
    token: sha256~XXXXXXXX
```
When launching the plugin I am not logged in, I get the login button.
