### ISSUE TITLE
Cluster not accessible even if I pick the correct config file

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#4874]
related to #4816

**Steps:**
1. ASSERT: have several config files. I created `kind.yaml` by launching the kind cluster via Podman Desktop, which created the file `config`. I then copied it over to `kind.yaml` and created `config` with the content that you see below:

`config`:
```yaml
---
apiVersion: "v1"
kind: "Config"
current-context: "kind-kind-cluster"
preferences: {}
```
`kind.yaml`:
```yaml
---
apiVersion: "v1"
kind: "Config"
clusters:
- cluster:
    certificate-authority-data: "XXXXX"
    server: "https://127.0.0.1:63039/"
  name: "kind-kind-cluster"
contexts:
- context:
    cluster: "kind-kind-cluster"
    namespace: "default"
    user: "kind-kind-cluster"
  name: "kind-kind-cluster"
current-context: "kind-kind-cluster"
preferences: {}
users:
- name: "kind-kind-cluster"
  user:
    client-certificate-data: "XXXXX"
    client-key-data: "XXXXXXX"
```
2. EXEC: launch vscode-openshift
3. ASSERT: you are prompted to select a config file
<img src="https://github.com/user-attachments/assets/de80c407-3172-4888-9929-1da28edaea30" width=600/>

4. EXEC: pick `kind.yaml`

**Result:**
vscode-openshift doesnt see my cluster.
<img src="https://github.com/user-attachments/assets/2c4b9069-11d5-467f-92c6-766b14f5ac10" width=400/>

`kind.yaml` is valid: if I copy `kind.yml` to `config`, vscode-openshift works fine:
<img src="https://github.com/user-attachments/assets/60b36fc5-2156-4dbe-89e0-5a9bd05ca0e2" width=400/>
