### ISSUE TITLE
Provide keybinding for all the commands

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-openshift-tools#820]
Key bindings will provide shortcut keys for Login, create, delete and etc.
for e.g:
```
Login: command/ctrl+shift+l
refresh: command/ctrl+shift+r
project
 - create: command/ctrl+shift+c+p
 - delete: command/ctrl+shift+d+p
appliction:
 - create: command/ctrl+shift+c+a
 - delete: command/ctrl+shift+d+a
```
will perform the action depend on the key press.
